version: '3'

services:

  db:
    image: "postgres:14"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - usufslc
    env_file:
      - .env

  prod:
    depends_on:
      - "db"
    build: .
    expose:
      - 5000
    volumes:
      - ./config:/app/config:ro
      - ./public:/app/public:ro
    networks:
      - usufslc
    environment:
      - APP_ENV=production

  nginx:
    depends_on:
      - "prod"
    build: ./nginx
    ports:
      - "8080:80"
      - "1935:1935"
    volumes:
      - /tmp/hls:/var/stream/hls:rw
      - /tmp/recordings:/var/stream/recordings:rw
    networks:
      - usufslc

volumes:
  pgdata:

networks:
  usufslc:
    driver: bridge
